/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADD_H_RPCGEN
#define _ADD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct intpair {
	int a;
	int b;
};
typedef struct intpair intpair;

#define CALCULATION_PROG 0x2fffffff
#define CALCULATION_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADDT 1
extern  int * addt_1(intpair *, CLIENT *);
extern  int * addt_1_svc(intpair *, struct svc_req *);
#define SUBT 2
extern  int * subt_1(intpair *, CLIENT *);
extern  int * subt_1_svc(intpair *, struct svc_req *);
#define MULTT 3
extern  int * multt_1(intpair *, CLIENT *);
extern  int * multt_1_svc(intpair *, struct svc_req *);
#define DIVT 4
extern  int * divt_1(intpair *, CLIENT *);
extern  int * divt_1_svc(intpair *, struct svc_req *);
extern int calculation_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADDT 1
extern  int * addt_1();
extern  int * addt_1_svc();
#define SUBT 2
extern  int * subt_1();
extern  int * subt_1_svc();
#define MULTT 3
extern  int * multt_1();
extern  int * multt_1_svc();
#define DIVT 4
extern  int * divt_1();
extern  int * divt_1_svc();
extern int calculation_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_intpair (XDR *, intpair*);

#else /* K&R C */
extern bool_t xdr_intpair ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADD_H_RPCGEN */
