/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

void add(CLIENT *clnt, int a, int b);
void subtract(CLIENT *clnt, int a, int b);
void multiply(CLIENT *clnt, int a, int b);
void divide(CLIENT *clnt, int a, int b);  

void
calculation_prog_1(char *host)
{

	int a, b, menu;
	CLIENT *clnt;
	int  *result_1;
	intpair  addt_1_arg;
	int  *result_2;
	intpair  subt_1_arg;
	int  *result_3;
	intpair  multt_1_arg;
	int  *result_4;
	intpair  divt_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULATION_PROG, CALCULATION_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	
#endif	/* DEBUG */
	while(1)
	{	
		printf("1: choose to add.\n");
		printf("2: choose to subtract.\n");
		printf("3: choose to multiply.\n");
		printf("4: choose to divide.\n");
		printf("5: Exit.\n");
		scanf("%d", &menu);
		
		switch (menu)
		{
			case 1:
				printf("Enter the first number:\n");
				scanf("%d", &a);

				printf("Enter the second number:\n");
				scanf("%d", &b);

				add(clnt, a, b);
				break;
			case 2:
				printf("Enter the first number:\n");
				scanf("%d", &a);

				printf("Enter the second number:\n");
				scanf("%d", &b);

				subtract(clnt, a, b);
				break;
			case 3:
				printf("Enter the first number:\n");
				scanf("%d", &a);

				printf("Enter the second number:\n");
				scanf("%d", &b);

				multiply(clnt, a, b);
				break;
			case 4:
				printf("Enter the first number:\n");
				scanf("%d", &a);

				printf("Enter the second number:\n");
				scanf("%d", &b);

				divide(clnt, a, b);
				break;
			case 5:
				break;
		}

	}

	

	result_1 = addt_1(&addt_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = subt_1(&subt_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = multt_1(&multt_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = divt_1(&divt_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void add(CLIENT *clnt, int a, int b) 
{ 
    int  *result; 
    intpair v;   
    v.a = a; 
    v.b = b; 
    result = addt_1(&v, clnt); 
    if (result == 0) 
	{ 
        clnt_perror(clnt, "call failed"); 
    	} 
    else 
	{ 
        printf(" The result is: %d\n", *result); 
    	} 

} 


void subtract(CLIENT *clnt, int a, int b) 
{ 
    int  *result; 
    intpair v;   
    v.a = a; 
    v.b = b; 
    result = subt_1(&v, clnt); 
    if (result == 0) 
	{ 
        clnt_perror(clnt, "call failed"); 
    	} 
    else 
	{ 
        printf(" The result is: %d\n", *result); 
    	} 

}

void multiply(CLIENT *clnt, int a, int b) 
{ 
    int  *result; 
    intpair v;   
    v.a = a; 
    v.b = b; 
    result = multt_1(&v, clnt); 
    if (result == 0) 
	{ 
        clnt_perror(clnt, "call failed"); 
    	} 
    else 
	{ 
        printf(" The result is: %d\n", *result); 
    	} 

} 
void divide(CLIENT *clnt, int a, int b) 
{ 
    int  *result; 
    intpair v;   
    v.a = a; 
    v.b = b; 
    result = divt_1(&v, clnt); 
    if (result == 0) 
	{ 
        clnt_perror(clnt, "call failed"); 
    	} 
    else 
	{ 
        printf(" The result is: %d\n", *result); 
    	} 

} 

 

int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calculation_prog_1 (host);
exit (0);
}
