/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADD_H_RPCGEN
#define _ADD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct intpair {
	int a;
	int b;
};
typedef struct intpair intpair;

#define CALCULATION_PROG 0x23451111
#define CALCULATION_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_1(intpair *, CLIENT *);
extern  int * add_1_svc(intpair *, struct svc_req *);
#define SUB 2
extern  int * sub_1(intpair *, CLIENT *);
extern  int * sub_1_svc(intpair *, struct svc_req *);
#define MULT 3
extern  int * mult_1(intpair *, CLIENT *);
extern  int * mult_1_svc(intpair *, struct svc_req *);
#define DIV 4
extern  int * div_1(intpair *, CLIENT *);
extern  int * div_1_svc(intpair *, struct svc_req *);
extern int calculation_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_1();
extern  int * add_1_svc();
#define SUB 2
extern  int * sub_1();
extern  int * sub_1_svc();
#define MULT 3
extern  int * mult_1();
extern  int * mult_1_svc();
#define DIV 4
extern  int * div_1();
extern  int * div_1_svc();
extern int calculation_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_intpair (XDR *, intpair*);

#else /* K&R C */
extern bool_t xdr_intpair ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADD_H_RPCGEN */
